#! /bin/sh

# unreal Start/stop the Unreal IRC server.

### BEGIN INIT INFO
# Provides:          ircd
# Required-Start:    $syslog
# Required-Stop:     $syslog
# Should-Start:      $local_fs $network $named
# Should-Stop:       $local_fs $network $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: UnrealIRCd daemon init.d script
# Description:       Use to manage the UnrealIRCd daemon.
### END INIT INFO

PATH=/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/var/lib/unreal/src/ircd
NAME=UnrealIRCd
USER=irc
GROUP=irc
PIDFILEDIR=/var/run/unrealircd
PIDFILE=/var/lib/unreal/ircd.pid
DESC="Unreal IRC Server"

test -f $DAEMON || exit 0

set -e

case "$1" in
  start)
        echo -n "Starting $NAME with pid $PIDFILE"
        start-stop-daemon --oknodo --start --quiet --exec $DAEMON \
                --user $USER -c $USER --pidfile "$PIDFILE" > /dev/null
        echo "."
        break
        ;;
  stop)
        if [ ! -r $PIDFILE ] ; then
          echo "ERROR: $NAME is not running"
          exit 1
        fi
        echo -n "Stopping $NAME"
        start-stop-daemon --pidfile "$PIDFILE" --oknodo --stop --quiet --signal 15 --exec $DAEMON
        echo "."
        break
        ;;
  status)
        PID=`ps -e | grep ircd | awk '{ print $1 }'`
        if [ -z $PID ] ; then
          echo "$NAME is not running."
        else
          echo "$NAME is running on pid $PID..."
        fi
        break
        ;;

  rehash)
        echo "Rehashing UnrealIRCd"
        if [ ! -r $PIDFILE ] ; then
          echo "ERROR: UnrealIRCd is not running"
          exit 1
        fi
        kill -1 `cat $PIDFILE`
        echo "."
        break
        ;;
  restart|force-reload)
        echo -n "Restarting $DESC: $NAME"
        if [ -f $PIDFILE ]; then
          start-stop-daemon --stop --quiet --pidfile $PIDFILE --signal 15 --exec $DAEMON
          sleep 1
        fi
        start-stop-daemon --start --quiet --user $USER -c $USER --pidfile $PIDFILE --exec $DAEMON > /dev/null
        echo "."
        break
        ;;
  *)
        echo "Usage: $0 {start|stop|restart|rehash|force-reload}" >&2
        exit 1
        ;;
esac

exit 0